config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :reviews, shallow: true
  root 'application#codeTest'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :review
    validates :name, presence: true
    validates :comment, presence: true
    
end

app/models/review.rb
class Review < ApplicationRecord
    has_many :comments
    validates :rating, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
    validates :name, presence: true
    validates :review, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def codeTest
    render html: "Homepage for code test"
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end


  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:name, :comment, :review_id)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  #def edit
  #end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  #def update
  #  respond_to do |format|
  #    if @review.update(review_params)
  #      format.html { redirect_to @review, notice: 'Review was successfully updated.' }
  #      format.json { render :show, status: :ok, location: @review }
  #    else
  #      format.html { render :edit }
  #      format.json { render json: @review.errors, status: :unprocessable_entity }
  #    end
  #  end
  #end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  #def destroy
  #  @review.destroy
  #  respond_to do |format|
  #    format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
  #    format.json { head :no_content }
  #  end
  #end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:date, :name, :review, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>

  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :comment_name %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment, id: :comment_comment %>
  </div>
  
 <div class="field">
    <%= form.hidden_field :review_id, id: :comment_review_id, value: params[:format] %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Comment</th>
      <th>Review</th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.name %></td>
        <td><%= comment.comment %></td>
        <td><%= comment.review_id %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', review_path(params[:format]) %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @comment.name %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @comment.comment %>
</p>

<p>
  <strong>Review:</strong>
  <%= @comment.review_id %>
</p>

<%= link_to 'Back', review_path(@comment.review_id) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodeTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_with(model: review, local: true) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :review_name %>
  </div>

  <div class="field">
    <%= form.label :review %>
    <%= form.text_area :review, id: :review_review %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating, id: :review_rating %>
  </div>

  <div class="actions">
    <%= form.submit "Submit" %>
  </div>
<% end %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Drover Reviews</h2>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Name</th>
      <th>Review</th>
      <th>Rating</th>
      <th>View</th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.created_at.strftime("%d %B %Y") %></td>
        <td><%= review.name %></td>
        <td><%= review.review %></td>
        <td><%= review.rating %></td>
        <td><%= link_to 'View', review %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Post a new Review', new_review_path %>

app/views/reviews/new.html.erb
<h3>New Review</h3>

<%= render 'form', review: @review %>

<%= link_to 'Back to reviews', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Drover Review</h2>

<p>
  <strong>Date:</strong>
  <%= @review.created_at.strftime("%d %B %Y") %>
</p>

<p>
  <strong>Name:</strong>
  <%= @review.name %>
</p>

<p>
  <strong>Review:</strong>
  <%= @review.review %>
</p>

<p>
  <strong>Rating (out of 5):</strong>
  <%= @review.rating %>
</p>

<% @review.comments.each do |comment| %>
  <p>Comment#<%= comment.id %></p>
  <ul>
    <li>Name: <%= comment.name %></li>
    <li>Comment: <%= comment.comment %></li>
  </ul>
<% end %>

<%= link_to 'Back to all reviews', reviews_path %>
<%= link_to 'Comment this review', new_comment_path(@review.id) %>